[build]
 functions = "./functions"

[functions]
node_bundler = "zisi"

[[redirects]]
 from = "/api/*"
 to = "/.netlify/functions/:splat"
 status = 200
 
 [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
